# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainForm.ui'
#
# Created by: PyQt5 UI code generator 5.15.10
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(693, 335)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.lab = QtWidgets.QLabel(self.centralwidget)
        self.lab.setGeometry(QtCore.QRect(10, 10, 161, 31))
        self.lab.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.lab.setObjectName("lab")
        self.txtProjectPath = QtWidgets.QLineEdit(self.centralwidget)
        self.txtProjectPath.setGeometry(QtCore.QRect(180, 10, 500, 31))
        self.txtProjectPath.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.txtProjectPath.setObjectName("txtProjectPath")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox.setGeometry(QtCore.QRect(10, 50, 671, 271))
        self.groupBox.setObjectName("groupBox")
        self.chkSMoverwriteMain = QtWidgets.QCheckBox(self.groupBox)
        self.chkSMoverwriteMain.setGeometry(QtCore.QRect(20, 20, 211, 20))
        self.chkSMoverwriteMain.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.chkSMoverwriteMain.setObjectName("chkSMoverwriteMain")
        self.chkSMaddModuleInSeprateFolder = QtWidgets.QCheckBox(self.groupBox)
        self.chkSMaddModuleInSeprateFolder.setGeometry(QtCore.QRect(310, 20, 291, 20))
        self.chkSMaddModuleInSeprateFolder.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.chkSMaddModuleInSeprateFolder.setObjectName("chkSMaddModuleInSeprateFolder")
        self.chkSMaddClassFile = QtWidgets.QCheckBox(self.groupBox)
        self.chkSMaddClassFile.setGeometry(QtCore.QRect(20, 60, 181, 20))
        self.chkSMaddClassFile.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.chkSMaddClassFile.setObjectName("chkSMaddClassFile")
        self.lab_2 = QtWidgets.QLabel(self.groupBox)
        self.lab_2.setGeometry(QtCore.QRect(20, 110, 140, 30))
        self.lab_2.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.lab_2.setObjectName("lab_2")
        self.txtSMmoduleName = QtWidgets.QLineEdit(self.groupBox)
        self.txtSMmoduleName.setGeometry(QtCore.QRect(170, 110, 490, 31))
        self.txtSMmoduleName.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.txtSMmoduleName.setObjectName("txtSMmoduleName")
        self.lab_3 = QtWidgets.QLabel(self.groupBox)
        self.lab_3.setGeometry(QtCore.QRect(20, 150, 140, 30))
        self.lab_3.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.lab_3.setObjectName("lab_3")
        self.txtSMclassName = QtWidgets.QLineEdit(self.groupBox)
        self.txtSMclassName.setGeometry(QtCore.QRect(170, 150, 490, 31))
        self.txtSMclassName.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.txtSMclassName.setObjectName("txtSMclassName")
        self.btnSMok = QtWidgets.QPushButton(self.groupBox)
        self.btnSMok.setGeometry(QtCore.QRect(430, 190, 111, 60))
        self.btnSMok.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.btnSMok.setObjectName("btnSMok")
        self.btn = QtWidgets.QPushButton(self.groupBox)
        self.btn.setGeometry(QtCore.QRect(550, 190, 111, 61))
        self.btn.setStyleSheet("font: 75 italic 12pt \"Calibri\";\n"
"text-decoration: underline;\n"
"color: rgb(200, 7, 85);\n"
"border:2px solid royalblue")
        self.btn.setObjectName("btn")
        self.chkSMaddUIfile = QtWidgets.QCheckBox(self.groupBox)
        self.chkSMaddUIfile.setGeometry(QtCore.QRect(310, 60, 151, 20))
        self.chkSMaddUIfile.setStyleSheet("font: 10pt \"MS Shell Dlg 2\";")
        self.chkSMaddUIfile.setObjectName("chkSMaddUIfile")
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.btn.clicked.connect(MainWindow.close) # type: ignore
        self.btnSMok.clicked.connect(MainWindow.btnSMOkClick) # type: ignore
        self.txtSMmoduleName.textChanged['QString'].connect(MainWindow.txtSMmoduleNameTextChange) # type: ignore
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.lab.setText(_translate("MainWindow", "Project Path"))
        self.groupBox.setTitle(_translate("MainWindow", "Module "))
        self.chkSMoverwriteMain.setText(_translate("MainWindow", "Overwrite  main.py "))
        self.chkSMaddModuleInSeprateFolder.setText(_translate("MainWindow", "Add module in separate folder "))
        self.chkSMaddClassFile.setText(_translate("MainWindow", "Add Class File"))
        self.lab_2.setText(_translate("MainWindow", "Module Name"))
        self.lab_3.setText(_translate("MainWindow", "Class Name"))
        self.btnSMok.setText(_translate("MainWindow", "OK"))
        self.btn.setText(_translate("MainWindow", "Close"))
        self.chkSMaddUIfile.setText(_translate("MainWindow", "Add UI File"))
